import { useState } from 'react';
import {
  apartments, flats, managementComplaints, maintenanceRequests, notices, payments, reports, tenants, utilityBills,
  type Apartment, type Tenant,
} from '../../../data/managerManagementData';
import ManagerSectionHeader from '../ManagerSectionHeader';
import StatusBadge from '../StatusBadge';
import { DetailDrawer, EmptyState, Feedback, FilterSelect, ModuleToolbar } from '../ManagerModuleElements';

const matches = (values: readonly string[], search: string) => values.some((value) => value.toLowerCase().includes(search.toLowerCase()));
const actionMessage = (action: string) => `${action} is ready for backend integration.`;

export function ApartmentsSection() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All statuses'); const [selected, setSelected] = useState<Apartment | null>(null); const [feedback, setFeedback] = useState('');
  const records = apartments.filter((item) => matches([item.name, item.address, item.contact ?? ''], search) && (status === 'All statuses' || item.status === status));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Portfolio" title="Apartment Management" description="Manage buildings, capacity, and property contacts." actionLabel="Add Apartment" actionIcon="bi-building-add" onAction={() => setFeedback(actionMessage('Add Apartment'))} /><Feedback message={feedback} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search apartments"><FilterSelect label="Property status" value={status} options={['All statuses', 'Active', 'Maintenance']} onChange={setStatus} /></ModuleToolbar>{records.length ? <div className="manager-property-grid">{records.map((item) => <article className="manager-property-card" key={item.id}><div className="manager-property-card__visual"><i className={`bi ${item.image}`} /><StatusBadge value={item.status} /></div><div className="manager-property-card__body"><span>{item.address}</span><h2>{item.name}</h2><div className="manager-property-metrics"><div><strong>{item.flats}</strong><small>Total flats</small></div><div><strong>{item.occupied}</strong><small>Occupied</small></div><div><strong>{item.vacant}</strong><small>Vacant</small></div></div><p><i className="bi bi-person" /> {item.contact}</p><button type="button" onClick={() => setSelected(item)}>View property <i className="bi bi-arrow-right" /></button></div></article>)}</div> : <EmptyState />}<DetailDrawer open={Boolean(selected)} title={selected?.name ?? ''} subtitle={selected?.address ?? ''} onClose={() => setSelected(null)}>{selected && <div className="manager-detail-grid"><div><span>Total flats</span><strong>{selected.flats}</strong></div><div><span>Occupied</span><strong>{selected.occupied}</strong></div><div><span>Vacant</span><strong>{selected.vacant}</strong></div><div><span>Status</span><StatusBadge value={selected.status} /></div><div className="manager-detail-grid__wide"><span>Property contact</span><strong>{selected.contact}</strong></div></div>}</DetailDrawer></div>;
}

export function FlatsSection() {
  const [search, setSearch] = useState(''); const [occupancy, setOccupancy] = useState('All occupancy'); const [property, setProperty] = useState('All apartments'); const [feedback, setFeedback] = useState('');
  const properties = ['All apartments', ...new Set(flats.map((item) => item.apartment))];
  const records = flats.filter((item) => matches([item.number, item.apartment, item.tenant], search) && (occupancy === 'All occupancy' || item.occupancy === occupancy) && (property === 'All apartments' || item.apartment === property));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Inventory" title="Flat Management" description="Track unit availability, residents, rent, and lease status." actionLabel="Add Flat" actionIcon="bi-plus-square" onAction={() => setFeedback(actionMessage('Add Flat'))} /><Feedback message={feedback} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search flats"><FilterSelect label="Occupancy" value={occupancy} options={['All occupancy', 'Occupied', 'Vacant', 'Maintenance']} onChange={setOccupancy} /><FilterSelect label="Apartment" value={property} options={properties} onChange={setProperty} /></ModuleToolbar><DataTable headers={['Flat', 'Apartment', 'Floor', 'Tenant', 'Monthly rent', 'Occupancy', 'Lease']}>{records.map((item) => <tr key={item.id}><td className="manager-table__primary">{item.number}</td><td>{item.apartment}</td><td>{item.floor}</td><td>{item.tenant}</td><td>{item.rent}</td><td><StatusBadge value={item.occupancy} /></td><td><StatusBadge value={item.lease} /></td></tr>)}</DataTable>{!records.length && <EmptyState />}</div>;
}

export function TenantsSection() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All accounts'); const [selected, setSelected] = useState<Tenant | null>(null); const [feedback, setFeedback] = useState('');
  const records = tenants.filter((item) => matches([item.name, item.flat, item.apartment, item.contact ?? ''], search) && (status === 'All accounts' || item.accountStatus === status));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Residents" title="Tenant Management" description="A central directory for residents, leases, and account health." actionLabel="Add Tenant" actionIcon="bi-person-plus" onAction={() => setFeedback(actionMessage('Add Tenant'))} /><Feedback message={feedback} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search tenants"><FilterSelect label="Account status" value={status} options={['All accounts', 'Active', 'Notice']} onChange={setStatus} /></ModuleToolbar><DataTable headers={['Tenant', 'Residence', 'Contact', 'Lease period', 'Rent', 'Account', '']} >{records.map((item) => <tr key={item.id}><td><div className="manager-person"><span>{item.name.split(' ').map((part) => part[0]).join('')}</span><strong>{item.name}</strong></div></td><td><strong>{item.flat}</strong><small>{item.apartment}</small></td><td>{item.contact}</td><td>{item.lease}</td><td><StatusBadge value={item.rentStatus} /></td><td><StatusBadge value={item.accountStatus} /></td><td><button className="manager-text-button" type="button" onClick={() => setSelected(item)}>View details</button></td></tr>)}</DataTable>{!records.length && <EmptyState />}<DetailDrawer open={Boolean(selected)} title={selected?.name ?? ''} subtitle={`${selected?.apartment ?? ''} · ${selected?.flat ?? ''}`} onClose={() => setSelected(null)}>{selected && <div className="manager-detail-grid"><div><span>Contact</span><strong>{selected.contact}</strong></div><div><span>Lease</span><strong>{selected.lease}</strong></div><div><span>Rent status</span><StatusBadge value={selected.rentStatus} /></div><div><span>Account</span><StatusBadge value={selected.accountStatus} /></div></div>}</DetailDrawer></div>;
}

export function RentSection() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All statuses'); const [month, setMonth] = useState('All months'); const [feedback, setFeedback] = useState('');
  const records = payments.filter((item) => matches([item.tenant, item.apartment, item.flat], search) && (status === 'All statuses' || item.status === status) && (month === 'All months' || item.month === month));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Finance" title="Rent Collection" description="Track monthly income, outstanding balances, and payment activity." actionLabel="Record Payment" actionIcon="bi-receipt" onAction={() => setFeedback(actionMessage('Record Payment'))} /><Feedback message={feedback} /><SummaryStrip items={[['Expected this month', null, 'bi-graph-up-arrow'], ['Collected', null, 'bi-check2-circle'], ['Pending payments', null, 'bi-hourglass-split'], ['Overdue balance', null, 'bi-exclamation-circle']]} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search payments"><FilterSelect label="Month" value={month} options={['All months']} onChange={setMonth} /><FilterSelect label="Payment status" value={status} options={['All statuses', 'Paid', 'Pending', 'Overdue']} onChange={setStatus} /></ModuleToolbar><DataTable headers={['Tenant', 'Apartment / Flat', 'Month', 'Amount', 'Due date', 'Payment date', 'Status']}>{records.map((item) => <tr key={item.id}><td className="manager-table__primary">{item.tenant}</td><td><strong>{item.flat}</strong><small>{item.apartment}</small></td><td>{item.month}</td><td>{item.amount ?? '—'}</td><td>{item.dueDate ?? '—'}</td><td>{item.paymentDate ?? '—'}</td><td><StatusBadge value={item.status} /></td></tr>)}</DataTable>{!records.length && <EmptyState />}</div>;
}

export function UtilitiesSection() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All statuses'); const [feedback, setFeedback] = useState('');
  const records = utilityBills.filter((item) => matches([item.tenant, item.flat, item.month], search) && (status === 'All statuses' || item.status === status));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Billing" title="Utility Bill Management" description="Review service charges and outstanding utility balances." actionLabel="Record Utility Bill" actionIcon="bi-plus-circle" onAction={() => setFeedback(actionMessage('Record Utility Bill'))} /><Feedback message={feedback} /><SummaryStrip items={[['Total billed', null, 'bi-receipt-cutoff'], ['Collected', null, 'bi-check2-circle'], ['Outstanding', null, 'bi-hourglass'], ['Overdue bills', null, 'bi-exclamation-circle']]} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search utility bills"><FilterSelect label="Billing status" value={status} options={['All statuses', 'Paid', 'Pending', 'Overdue']} onChange={setStatus} /></ModuleToolbar><DataTable headers={['Tenant / Flat', 'Electricity', 'Water', 'Gas', 'Month', 'Total', 'Due date', 'Status']}>{records.map((item) => <tr key={item.id}><td><strong>{item.tenant}</strong><small>{item.flat}</small></td><td>{item.electricity ?? '—'}</td><td>{item.water ?? '—'}</td><td>{item.gas ?? '—'}</td><td>{item.month}</td><td className="manager-table__primary">{item.total ?? '—'}</td><td>{item.dueDate ?? '—'}</td><td><StatusBadge value={item.status} /></td></tr>)}</DataTable>{!records.length && <EmptyState />}</div>;
}

export function ComplaintsSection() {
  const [tab, setTab] = useState<'complaints' | 'maintenance'>('complaints'); const [feedback, setFeedback] = useState('');
  const recordsAvailable = tab === 'complaints' ? managementComplaints.length > 0 : maintenanceRequests.length > 0;
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Service desk" title="Complaints & Maintenance" description="Coordinate resident support and property service work." actionLabel="Create Work Item" actionIcon="bi-plus-lg" onAction={() => setFeedback(actionMessage('Create Work Item'))} /><Feedback message={feedback} /><div className="manager-segments" role="tablist" aria-label="Service desk view"><button type="button" role="tab" aria-selected={tab === 'complaints'} className={tab === 'complaints' ? 'active' : ''} onClick={() => setTab('complaints')}>Complaints <span>—</span></button><button type="button" role="tab" aria-selected={tab === 'maintenance'} className={tab === 'maintenance' ? 'active' : ''} onClick={() => setTab('maintenance')}>Maintenance Requests <span>—</span></button></div>{tab === 'complaints' ? <DataTable headers={['Complaint', 'Tenant / Flat', 'Category', 'Priority', 'Submitted', 'Status']}>{managementComplaints.map((item) => <tr key={item.id}><td className="manager-table__primary">{item.title}</td><td><strong>{item.tenant}</strong><small>{item.flat}</small></td><td>{item.category}</td><td><StatusBadge value={item.priority} /></td><td>{item.submitted ?? '—'}</td><td><StatusBadge value={item.status} /></td></tr>)}</DataTable> : <DataTable headers={['Request', 'Property / Flat', 'Assigned to', 'Priority', 'Date', 'Status']}>{maintenanceRequests.map((item) => <tr key={item.id}><td className="manager-table__primary">{item.title}</td><td>{item.property}</td><td>{item.assigned ?? '—'}</td><td><StatusBadge value={item.priority} /></td><td>{item.date ?? '—'}</td><td><StatusBadge value={item.status} /></td></tr>)}</DataTable>}{!recordsAvailable && <EmptyState />}</div>;
}

export function NoticesSection() {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState('All categories'); const [feedback, setFeedback] = useState('');
  const categories = ['All categories', ...new Set(notices.map((item) => item.category))]; const records = notices.filter((item) => matches([item.title, item.description, item.audience], search) && (category === 'All categories' || item.category === category));
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Communications" title="Notice Management" description="Create and manage clear updates for residents." actionLabel="Publish Notice" actionIcon="bi-megaphone" onAction={() => setFeedback(actionMessage('Publish Notice'))} /><Feedback message={feedback} /><ModuleToolbar search={search} onSearch={setSearch} searchLabel="Search notices"><FilterSelect label="Category" value={category} options={categories} onChange={setCategory} /></ModuleToolbar>{records.length ? <div className="manager-notice-grid">{records.map((item) => <article className="manager-notice-card" key={item.id}><div><span className="manager-notice-card__icon"><i className="bi bi-megaphone" /></span><StatusBadge value={item.status} /></div><span>{item.category} · {item.audience}</span><h2>{item.title}</h2><p>{item.description}</p><footer><time>{item.published}</time><button type="button" onClick={() => setFeedback(actionMessage(`Edit ${item.title}`))}>Manage <i className="bi bi-arrow-right" /></button></footer></article>)}</div> : <EmptyState />}</div>;
}

export function ReportsSection() {
  const [feedback, setFeedback] = useState('');
  return <div className="manager-section"><ManagerSectionHeader eyebrow="Insights" title="Reports" description="Generate focused operational summaries for your portfolio." /><Feedback message={feedback} />{reports.length ? <div className="manager-report-grid">{reports.map((item) => <article className="manager-report-card" key={item.id}><span className="manager-report-card__icon"><i className={`bi ${item.icon}`} /></span><h2>{item.title}</h2><p>{item.description}</p><label><span>Date range</span><select defaultValue={item.range ?? ''} aria-label={`${item.title} date range`}><option value="">Not available</option></select></label><button type="button" onClick={() => setFeedback(actionMessage(`Generate ${item.title}`))}>Generate report <i className="bi bi-arrow-up-right" /></button></article>)}</div> : <EmptyState title="No reports available" description="Reports can be generated after verified portfolio data is connected." />}</div>;
}

function DataTable({ headers, children }: { headers: readonly string[]; children: React.ReactNode }) {
  return <div className="manager-panel manager-data-panel"><div className="table-responsive manager-table-wrap"><table className="table manager-table align-middle mb-0"><thead><tr>{headers.map((header) => <th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>;
}

function SummaryStrip({ items }: { items: readonly (readonly [string, string | null, string])[] }) {
  return <div className="manager-summary-strip">{items.map(([label, value, icon]) => <article key={label}><span><i className={`bi ${icon}`} /></span><div><small>{label}</small><strong>{value ?? '—'}</strong></div></article>)}</div>;
}
